### ISSUE TITLE
not work with leptos

### ISSUE THREAD

**Issue by KhaledHosseini** [quay-rs/ethers-web#13]
mismatched types
   --> \.cargo\registry\src\index.crates.io-6f17d22bba15001f\ethers-web-0.2.0\src\leptos.rs:115:36
let ethereum = builder.url("http://localhost").build();
    |                                --- ^^^^^^^^^^^^^^^^^^ expected `Url`, found `&str`

**Comment by day01** [comment]
Thank you for your report. We are currently in the process of migrating from Ethers to Alloy, but everything should still be functioning as expected. I am working on a fix for these issues.

**Comment by day01** [comment]
version 0.2.1 is published.
https://crates.io/crates/ethers-web/0.2.1

I have to mark that we don't have yet `Proper Leptos support` :)
